version: "3.6"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: changeme
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7

volumes:
  db_data:
